# Generated by Django 4.2.4 on 2023-08-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('workers_count', models.IntegerField()),
                ('games_count', models.PositiveIntegerField()),
            ],
        ),
    ]
