# Generated by Django 4.2.4 on 2023-08-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='games_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studio',
            name='workers_count',
            field=models.IntegerField(default=0),
        ),
    ]
